catboost_params:
  iterations: 100
  learning_rate: 0.1
  loss_function: MultiClass
  task_type: CPU
model_version: 1
number_words_after: 6
number_words_before: 6
refit_model: false
logging_level: stats
smart_split: true
use_calculated_parameters: true
use_weights: false
calculated_parameters_weight: none
use_initial_form: true
lemmer_type: smalt_stemmer
excluded_attributes:
  - 109
  - 110
excluded_attribute_values:
  - 384
  - 385
  - 386
  - 387
  - 388
  - 389
  - 390
  - 391
  - 392
  - 393
  - 394
  - 395
  - 397
  - 398
  - 399
  - 400
  - 401